- name: feat
  color: 14b8a6
  description: 새로운 기능 추가 (Feature)

- name: enhancement
  color: 22c55e
  description: 기능 개선/향상 (Enhancement)

- name: fix
  color: f43f5e
  description: 버그 수정 (Fix)

- name: hotfix
  color: 0ea5e9
  description: 긴급 핫픽스 (Hotfix)

- name: chore
  color: 64748b
  description: 유지보수/빌드/잡무 (Chore)

- name: refactor
  color: d946ef
  description: 리팩터링 (Refactor)

- name: ci
  color: 0369a1
  description: CI/CD 파이프라인/워크플로 변경 (CI)

- name: skip-release
  color: 94a3b8
  description: 자동 릴리스 노트에서 제외할 때 사용
